version: '3'

networks: 
  default: 
    external: 
      name: balancefynet

services:

# FRONTEND
  frontend1:
    image: ${FRONTEND_IMAGE_VERSION}
    env_file:
      - ../.env

  frontend2:
    image: ${FRONTEND_IMAGE_VERSION}
    env_file:
      - ../.env

  loadbalance:
    build: .
    volumes:
      - /etc/letsencrypt/live/api-balancefy.ddns.net/cert.pem:/etc/nginx/conf.d/cert.pem
      - /etc/letsencrypt/live/api-balancefy.ddns.net/privkey.pem:/etc/nginx/conf.d/privkey.pem
    depends_on:
      - frontend1
      - frontend2
    ports:
      - 80:80
      - 443:443
