version: '3'

networks: 
  default: 
    external: 
      name: balancefynet

volumes:
  db:

services:

# BACKEND
  backend:
    image: ${BACKEND_IMAGE_VERSION}
    restart: always
    depends_on:
      - balancefydb
    ports:
      - 8080:8080
    

  balancefydb:
    image: postgres:10.5
    restart: always
    env_file:
      - ../.env
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/mysql
      - ../db/migration.sql:/docker-entrypoint-initdb.d/migration.sql
