version: '3'

volumes:
  jenkins_home:

services:
  jenkins: 
    build: .
    ports:
      - 8081:8080
      - 50000:50000
    volumes:
      - ../:/infra
      - /var/run/docker.sock:/var/run/docker.sock
      - jenkins_home:/var/jenkins_home
      
